Util: parseExternalLinks() no longer accepts null, requires a string
The main caller is Intuition::msg() which already returns early
before calling parseExternalLinks(), if the value was null.

This makes the tests pass on PHP 8.0, which currenlty fail due to:

> TypeError: preg_replace_callback():
> Argument #3 ($subject) must be of type array|string, null given

This could be supported with a simple check, but I'm removing it
instead.